mp_quotes_list = ['Who goes there?',
 'Pull the other one!',
 'We have ridden the length and breadth of the land in search of knights who will join me in my court at Camelot.',
 "What, ridden on a horse?",
 "You are using coconuts!",
 "You have got two empty halves of coconut and you are banging them together.",
 "Where did you get the coconut?",
 "We found them",
 'Are you suggesting coconuts migrate?',
 'Not at all, they could be carried.',
 'Listen, in order to maintain air-speed velocity, a swallow needs to beat its wings 43 times every second, right?',
 'I am not interested!',
 "It could be carried by an African swallow!",
 'Will you ask your master if he wants to join my court at Camelot?!',
 'Wait a minute. Supposing two swallows carried it together?',
 'Bring out your dead!',
 "I am not dead!",
 "he says he is not dead!",
 "You will be stone dead in a moment."
 "It is against regulations",
 "I am getting better!",
 "I don't want to go in the cart!",
 "Oh, don't be such a baby.",
 'I feel fine!',
 "Naaah, I got to go on to Robinson's. They have lost nine today.",
 "You are not fooling anyone you know.",
 'I feel happy. I feel happy.',
 "Who is that then?",
 "He has not got shit all over him",
 'Old woman!',
 "What knight lives in that castle over there?",
 "I'm thirty seven. I'm not old!",
 "Well, I can't just call you `Man'.",
 "Well, you could say `Dennis'.",
 "I did say sorry about the `old woman,' but from the behind you looked--",
 "Well, I AM king...",
 "Oh king, eh, very nice.",
 "And how did you get that, eh? By exploiting the workers",
 "by hanging on to outdated imperialist dogma which perpetuates the economic and social differences in our society!",
 "If there is ever going to be any progress--",
 "Dennis, there is some lovely filth down here.",
 'King of the who?',
 'Who are the Britons?',
 "we are all Britons and I am your king."
 "I  did not know we had a king. I thought we were an autonomous collective.",
 "You are fooling yourself. We are living in a dictatorship.",
 'A self-perpetuating autocracy in which the working classes--',
 "Oh there you go, bringing class into it again.",
 "That is what it is all about if only people would--",
 "Who lives in that castle?",
 'No one lives there.',
 "We do not have a lord.",
 "We are an anarcho-syndicalist commune.",
 'But all the decisions of that officer have to be ratified at a special biweekly meeting.',
 'By a simple majority in the case of purely internal affairs,--',
 'I order you to be quiet!',
 'I am your king!',
 "Well, I did not vote for you."
 "Well, How did you become king then?",
 'strange women lying in ponds distributing swords is no basis for a system of government.',
 "Well you can not expect to wield supreme executive power just because some watery tart threw a sword at you!",
 "I mean, if I went around saying I was an empereror just because some moistened bink had lobbed a scimitar at me they would put me away!",
 'now we see the violence inherent in the system.',
 'Oh! Come and see the violence inherent in the system!',
 "HELP! HELP! I am being repressed!",
 'Bloody peasant!',
 'Oh, what a give away. Did you here that, did you hear that, eh?',
 "That is what I am on about",
 "did you see him repressing me?"
 'You fight with the strength of many men, Sir Knight.',
 'None shall pass.',
 'I move for no man.',
 "It is but a scratch.",
 'Come on you pansy!',
 'Victory is mine!',
 "Look, you stupid bastard, you have got no arms left.",
 "Just a flesh wound."
 'What are you going to do, bleed on me?',
 "You are a loony.",
 "All right; we will call it a draw.",
 "Oh, oh, I see, running away, eh?",
 "You yellow bastards! Come back here and take what is coming to you.",
 "I will bite your legs off!",
 'We have found a witch, might we burn her?',
 "How do you know she is a witch?",
 "I am not a witch.",
 'They dressed me up like this.',
 'Well, we did do the nose.',
 'Did you dress her up like this?',
 "What makes you think she is a witch?",
 'Well, she turned me into a newt.',
 "I got better.",
 'what do you do with witches?',
 'So, how do we tell whether she is made of wood?',
 'What also floats in water?',
 "Very small rocks!",
 'A duck.',
 "Exactly! So, logically...,",
 'Right, remove the supports!',
 "It's a fair cop.",
 "Who are you who are so wise in the ways of science?",
 "The wise Sir Bedevere was the first to join King Arthur's knights, but other illustrious names were soon to follow: Sir Launcelot the Brave; Sir Galahad the Pure; and Sir Robin the Not-quite-so-brave-as-Sir-Launcelot who had nearly fought the Dragon of Angnor,who had nearly stood up to the viscious Chicken of Bristol and who had personally wet himself at the Battle of Badon Hill; and the aptly named Sir Not-appearing-in-this-film. Together they formed a band whose names and deeds were to be retold throughout the centuries, the Knights of the Round Table.",
 'And that, my liege, is how we know the Earth to be banana-shaped.',
 "Camelot!"
 "It is only a model."
 "Well, on second thought, let's not go to Camelot -- it is a silly place.",
 'Arthur! Arthur, King of the Britons!',
 "Every time I try to talk to someone it's 'sorry this' and 'forgive me that' and 'I'm not worthy'.",
 "I'm averting my eyes, oh Lord.",
 'Good idea, oh Lord!',
 'That is your purpose, Arthur the Quest for the Holy Grail.',
 "Allo! Who is zis?",
 "Whose castle is this?",
 "This is the castle of my master, Guy de Loimbard!",
 'Go and tell your master that we have been charged by God with a sacred quest.',
 "He says they have already got one!",
 "I am French! Why do think I have this outrageous accent, you silly king!",
 'What are you doing in England?',
 "Mind your own business!",
 "You do not frighten us, English pig-dogs!",
 'Go and boil your bottoms, sons of a silly person',
 'I blow my nose at you, so-called Arthur-king, you and all your silly English knights!',
 'What a strange person.',
 "I do not want to talk to you no more, you empty headed animal food trough wiper!",
 'I fart in your general direction!',
 'Your mother was a hamster and your father smelt of elderberries!',
 'No, now go away or I shall taunt you a second time!',
 'Fetchez la vache!',
 'Ah, this one is for your mother!',
 'Run away!',
 "Halt! Who art thou?",
 "He is brave Sir Robin, brave Sir Robin, who--",
 "Oh stop bitching and let's go have tea.",
 "All right all right all right we will kill him first and then have tea and biscuits.",
 "He buggered off.",
 "Brave Sir Robin ran away",
 "Bravely ran away away",
 "When danger reared its ugly head, He bravely turned his tail and fled",
 "He beat a very brave retreat",
 'Oh! but we are nice and we shall attend to your every, every need!',
 'Prepare a bed for our guest.',
 'Mine is Zoot... just Zoot.',
 'Oh, I am afraid our life must seem very dull and quiet compared to yours. We are but eight score young blondes and brunettes, all between sixteen and nineteen and a half, cut off in this castle with no one to protect us! Oh, it is a lonely life -- bathing, dressing, undressing, making exciting underwear....',
 'Try to relax.',
 'Torment me no longer!',
 "I am Zoot's identical twin sister, Dingo.",
 'I seek the Grail! I have seen it, here in this castle!',
 'bad, naughty Zoot!',
 'She has been setting alight to our beacon, which, I just remembered, is grail-shaped.',
 'You must tie her down on a bed and spank her!',
 'You must spank her well. And after you have spanked her, you may deal with her as you like. And then, spank me.',
 'Yes, yes, you must give us all a good spanking!',
 "You are in great peril!",
 "Silence, foul temptress!",
 "I can defeat them! There is only a hundred and fifty of them!",
 'Oh, shit.',
 'We were in the nick of time, you were in great peril.',
 'Look, let me go back in there and face the peril.',
 'Well, let me have just a little bit of peril?',
 "Bet you are gay!",
 "Oh, that's an unladen swallow's flight, obviously. I mean, they were more than two laden swallow's flights away -- four, really, if they had a coconut on a line between them. I mean, if the birds were walking and dragging--",
 'Get on with it!',
 'He knows of a cave, a cave which no man has entered.',
 'There is much danger, for beyond the cave lies the Gorge of Eternal Peril, which no man has ever crossed.',
 'Seek you the Bridge of Death.',
 'We are the Knights Who Say... Ni!',
 'No! Not the Knights Who Say Ni!',
 'We are the keepers of the sacred words: Ni, Ping, and Nuu-wom!',
 "The Knights Who Say Ni demand a sacrifice!",
 'Knights of Ni, we are but simple travellers who seek the enchanter who lives beyond these woods.',
 "We shall say 'Ni' again to you if you do not appease us.",
 'We want... a shrubbery!',
 "You must return here with a shrubbery or else you will never pass through this wood alive!",
 'O Knights of Ni, you are just and fair, and we will return with a shrubbery.',
 'One day, lad, all this will be yours!',
 'But, Mother--',
 "I do not want any of that.",
 "I have built this kingdom up from nothing. When I started here, all there was was swamp. The king said I was daft to build a castle in a swamp, but I built it all the same, just to show 'em. It sank into the swamp. So, I built a second one. That sank into the swamp. So I built a third one. That burned down, fell over, then sank into the swamp. But the fourth one stayed up. An' that's what your gonna get, lad -- the strongest castle in these islands.",
 "But I don't want any of that",
 "Stop that, stop that! You're not going to do a song while I'm here.",
 'Listen, Alice...',
 'We live in a bloody swamp. We need all the land we can get.',
 "she's got huge... tracts of land.",
 "can he leave the room with us?",
 '"To whoever finds this note, I have been imprisoned by my father, who wishes me to marry against my will. Please, please, please come and rescue me. I am in the tall tower of Swamp Castle." At last! A call, a cry of distress! This could be the sign that leads us to the Holy Grail!',
 'Brave, brave Concorde! You shall not have died in vain!',
 'I will send help as soon as I have accomplished a daring and heroic rescue in my own particular...',
 "I'll-uh, I'll just stay here, then, shall I, sir? Yeah.",
 "They cost fifty pounds each.",
 "O fair one, behold your humble servant Sir Launcelot of Camelot. I have come to take -- oh, I'm terribly sorry.",
 'You killed eight wedding guests in all!',
 "You only killed the bride's father, that's all!",
 'Pretty nice castle, Camelot. Uh, pretty good pig country....',
 "Um, I think when I'm in this idiom, I sometimes get a bit, uh, sort of carried away.",
 'Oh, bloody hell.',
 "He's killed the best man!",
 'He killed my auntie!',
 "Let's not bicker and argue about who killed who.",
 'For, since the tragic death of her father--',
 'And I want his only daughter to look upon me... as her own dad -- in a very real, and legally binding sense.',
 'Look! The dead Prince!',
 'You fell out of the Tall Tower, you creep!',
 'Quickly, sir! Come this way!!!',
 'Excuse me, could, uh, could somebody give me a push,',
 "No! Never! We have no shrubberies here.",
 "If you do not tell us where we can buy a shrubbery, my friend and I will say... we will say... `Ni!'.",
 "No, no -- 'ni!'. You're not doing it properly.",
 "Are you saying 'ni' to that old woman?",
 'There is a pestilence upon this land,',
 'Even those who arrange and design shrubberies are under considerable economic stress at this period in history.',
 'I am a shrubber. My name is Roger the Shrubber. I arrange, design, and sell shrubberies.',
 'Knights of Ni, we have brought you your shrubbery. May we go now?',
 'another shrubbery!',
 'Not another shrubbery!',
 'you must cut down the mightiest tree in the forest... with... a herring!',
 'Cut down a tree with a herring?',
 "How can we not say the word if you don't tell us what it is?",
 "My liege, it's Sir Robin!",
 "And sneaking away and buggering off",
 'No, it is far from--',
 'And so Arthur and Bedevere and Sir Robin set out on their search to find the enchanter of whom the old man had spoken in Scene 24.',
 "In the frozen land of Nador they were forced to eat Robin's minstrels. And there was much rejoicing.",
 'Summer changed back into Winter. And Winter gave Spring and Summer a miss and went straight on into Autumn.',
 'What manner of man are you that can summon up fire without flint or tinder?',
 "Greetings, Tim the Enchanter.",
 'You seek the Holy Grail!',
 'You know much that is hidden, O Tim.',
 "Yes, we're, we're looking for the Holy Grail. Our quest is to find the Holy Grail.",
 'Uh, so, uh, anything you can do to, uh, to help, would be... very... helpful...',
 'A Grail?!',
 "So, brave knights, if you do doubt your courage or your strength, come no further,",
 'death awaits you all with nasty big pointy teeth.',
 'What an eccentric performance.',
 'Behold the cave of Caerbannog!',
 'Right! Keep me covered.',
 'What, behind the rabbit?',
 'You silly sod!',
 "Well, that's no ordinary rabbit. That's the most foul, cruel, and bad-tempered rodent you ever set eyes on.",
 'You tit! I soiled my armor I was so scared!',
 "that rabbit has got a vicious streak a mile wide, it's a killer!",
 "It'll do you up a treat, mate!",
 "What does he do, nibble your bum?",
 "He's got huge, sharp-- he can leap about-- look at the bones!",
 "One rabbit stew coming right up!",
 'Jesus Christ!',
 "I warned you! But did you listen to me? Oh, no, you knew it all, didn't you? Oh, it's just a harmless little bunny, isn't it?",
 'Run away! Run away!',
 'How many did we lose?',
 "And we'd better not risk another frontal assault, that rabbit's dynamite.",
 'Oh, shut up and go and change your armor.',
 'We have the Holy Hand Grenade.',
 'The Holy Hand Grenade of Antioch!',
 'Consult the book of armaments.',
 "'Oh, Lord, bless this thy hand grenade that with it thou mayest blow thy enemies to tiny bits, in thy mercy.'",
 "And the Lord did grin, and people did feast upon the lambs, and sloths, and carp, and anchovies, and orangutans, and breakfast cereals, and fruit bats, and large --",
 "First shalt thou take out the Holy Pin. Then, shalt thou count to three, no more, no less. Three shall be the number thou shalt count, and the number of the counting shalt be three. Four shalt thou not count, nor either count thou two, excepting that thou then proceed to three. Five is right out. Once the number three, being the third number, be reached, then lobbest thou thy Holy Hand Grenade of Antioch towards thou foe, who being naughty in my sight, shall snuff it.",
 'Right! One... two... five!',
 "Three sir.",
 "'... the Castle of uuggggggh'.",
 "Look, if he was dying, he wouldn't bother to carve 'aaggggh'. He'd just say it!",
 'Perhaps he was dictating.',
 "Isn't there a Saint Aauuuves in Cornwall?",
 'There it is! The Bridge of Death!',
 'He asks each traveller five questions--',
 'Good luck, brave Sir Launcelot. God be with you.',
 "Stop! Who would cross the Bridge of Death must answer me these questions three, 'ere the other side he see.",
 "Ask me the questions, bridge-keeper. I'm not afraid.",
 'What is your name?',
 'What is your quest?',
 'What is your favorite color?',
 'Right. Off you go.',
 'What is the capital of Assyria?',
 'What is the air-speed velocity of an unladen swallow?',
 'What do you mean? An African or European swallow?',
 "What? I don't know that! Aaaaaaaaaa!",
 'How do know so much about swallows?',
 "Well, you have to know these things when you're a king you know.",
 'I one more time-a unclog my nose in your direction, sons of a window-dresser!',
 'I wave my private parts at your aunties,',
 'you cheesy lot of second hand electric donkey bottom biters.',
 'No chance, English bedwetting types.',
 "You tiny-brained wipers of other people's bottoms!",
 'we fire arrows at the tops of your heads and make castanets out of your testicles already! Ha ha!',
 "And now remain gone illegitimate faced buggerfolk! And, if you think you got nasty taunting this time, you ain't heard nothing yet! Daffy English kniggets!",
 'French persons! Today the blood of many a valiant knight shall be avenged.']

correct_answer_quotes = ['You fight with the strengths of many Knights, Sir!',
                        'You are so wise on the things about science and language, Sir!',
                        "You are braver than sir Launcelot, Sir!"]
wrong_answer_quotes = ['Are you an offspring of silly persons?',
                        'You may get a second taunt if you do this again.',
                        'Bad, Bad Zoot. Were you fooled by a beacon?',
                        "I'm just asking you to guess a letter, not the capital of Mercea.",
                        "Is there pestulence in your land. You can't even guess a letter?",
                        "One more mistake, you will be cast under the bridge."]
